In [1]:
import numpy as np
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)




TensorFlow 2.x selected.
<module 'tensorflow_core._api.v2.version' from '/tensorflow-2.1.0/python3.6/tensorflow_core/_api/v2/version/__init__.py'>


#Create Tensors

In [0]:
string = tf.Variable('this is a string', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [3]:
rank1_tensor = tf.Variable(['Test'], tf.string)
rank2_tensor = tf.Variable([['test', 'ok'], ['test', 'yes']], tf.string)

tf.rank(rank1_tensor),tf.rank(rank2_tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [4]:
rank1_tensor.shape, rank2_tensor.shape

(TensorShape([1]), TensorShape([2, 2]))

In [5]:
tensor1 = tf.ones([1,2,3]) ## tf.ones() creates a shape [1,2,3] tensor full of ones
# 1 bigger list, 2 list within the bigger list with 3 elements in each of the 2 smaller lists.
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshaping exisitng data to shapee [2,3,1]
# 2 big list, 3 small list in each  with 1 element.
tensor3 = tf.reshape(tensor2, [3,-1]) #-1 tell the tensor to calculate the size of the dimension in that place 
                                      # this will reshape the tensor to [3,2]
# The number of elements in the reshaped tensor MUST match the number in the original

print(tensor1)
print(tensor2)
print(tensor3)  

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Types of Tensors
*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the exception of **Variable** all of these tensors are immutable.



# Evaluating Tensor

Need to run a *session* to evaluate the tensor.
There are other ways to achieve this as well.

```
with tf.compat.v1.Session() as sess: # creates a session using the default graph
   tensor.eval() # tensor will of course be the name your tensor
```



In [0]:
t = tf.zeros([5,5,5,5])
# print(t)
t = tf.reshape(t, [625])
# print(t)
t = tf.reshape(t, [125, -1])
# print(t)